name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order:
      - course_advanced_dbt
      - dbt_snowflake_monitoring
      - dbt

query-comment:
  comment: '{{ dbt_snowflake_monitoring.get_query_comment(node) }}'
  append: true # Snowflake removes prefixed comments.

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

    staging:
      +schema: staging

    intermediate:
      +schema: intermediate

    marts:
      core:
        +schema: core_reporting
      finance:
        +schema: finance
      product:
        +schema: product

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
  unit_tests__fct_mrr:
    +schema: unit_testing
    +tags: unit_testing
    uunit_test__input__int_dates:
      +column_types:
        calendar_date: DATE
        day_of_month: INT
    unit_test__input__dim_subscription:
      +column_types:
        subscription_id: INT
        subscription_plan_id: INT
        user_id: INT
        starts_at: TIMESTAMP
        ends_at: TIMESTAMP
        plan_name: STRING
        pricing: FLOAT
        billing_period: STRING
    unit_test__output__fct_mrr:
      +column_types:
        surrogate_key: STRING
        date-month: DATE
        user_id: INT
        subscription_id: INT
        starts_at: TIMESTAMP
        ends_at: TIMESTAMP
        plan_name: STRING
        mrr_amount: FLOAT
        mrr_change: FLOAT
        retained_mrr_amount: FLOAT
        previous_month_mrr_amount: FLOAT
        change_category: STRING
        month_retained_number: INT

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
